version: "3.9"

services:
  oracle-db:
    # la imagen gvenzl/oracle-xe ejecuta createAppUser si pasas APP_USER/APP_USER_PASSWORD (útil para no conectar como SYS/SYSTEM)
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=Admin123
      - APP_USER=hotel_user
      - APP_USER_PASSWORD=hotel_pass
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - ./db/init.sql:/container-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM dual;' | sqlplus -s system/${ORACLE_PASSWORD}@//localhost:1521/XEPDB1 | grep -i 1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  backend:
    build: ./backend
    container_name: hotel_backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XEPDB1ue
      - SPRING_DATASOURCE_USERNAME=hotel_user
      - SPRING_DATASOURCE_PASSWORD=hotel_pass
      - JWT_SECRET=StrongRandomSecret
    depends_on:
      oracle-db:
        condition:service-healthy
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: hotel-frontend
    environment:
      - API_BASE_URL:http://localhost:8080/API_BASE_URL
    depends-on:
      - backend
    ports:
      - "4200:80" 